"""

Revision ID: 2ee7988ae58f
Revises: 1478ee321f08
Create Date: 2022-09-09 22:36:31.171355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee7988ae58f'
down_revision = '1478ee321f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('usual_dosage', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True, comment='Aqui pode colocar alguma dica de uso em pediatria, ou melhor aplicação de antibioticoterapia, além de restrição de uso'),
    sa.Column('kind', sa.Enum('male', 'fema', name='sexenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resting_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spO2', sa.Integer(), nullable=True),
    sa.Column('pain', sa.Integer(), nullable=True),
    sa.Column('sistolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('cardiac_freq', sa.Integer(), nullable=True),
    sa.Column('respiratory_freq', sa.Integer(), nullable=True),
    sa.Column('celcius_axillary_temperature', sa.Integer(), nullable=True),
    sa.Column('glucose', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('initial_date', sa.Date(), nullable=True),
    sa.Column('ending_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('admission_hour', sa.Time(), nullable=True),
    sa.Column('hpi', sa.Text(), nullable=False, comment='History of the Present Illness / HMA'),
    sa.Column('waiting_vacancy', sa.Boolean(), nullable=True, comment='Aguardando vaga na Regulação'),
    sa.Column('regulation_code', sa.String(), nullable=True, comment='Número de registro da regulação'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True, comment='Evolução do paciente com exame físico e sinais vitais'),
    sa.Column('professional', sa.Integer(), nullable=False),
    sa.Column('internment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['internment_id'], ['internments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('evolutions', sa.Column('professional', sa.Integer(), nullable=False))
    op.add_column('evolutions', sa.Column('internment_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'evolutions', type_='foreignkey')
    op.create_foreign_key(None, 'evolutions', 'internments', ['internment_id'], ['id'])
    op.drop_column('evolutions', 'patient_id')
    op.add_column('patients', sa.Column('comorbidities', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.drop_column('patients', 'admission_hour')
    op.drop_column('patients', 'hpi')
    op.drop_column('patients', 'waiting_vacancy')
    op.drop_column('patients', 'admission_date')
    op.drop_column('patients', 'pendings')
    op.drop_column('patients', 'regulation_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('regulation_code', sa.VARCHAR(), nullable=True))
    op.add_column('patients', sa.Column('pendings', sa.TEXT(), nullable=False))
    op.add_column('patients', sa.Column('admission_date', sa.DATE(), nullable=False))
    op.add_column('patients', sa.Column('waiting_vacancy', sa.BOOLEAN(), nullable=True))
    op.add_column('patients', sa.Column('hpi', sa.TEXT(), nullable=False))
    op.add_column('patients', sa.Column('admission_hour', sa.TIME(), nullable=True))
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'comorbidities')
    op.add_column('evolutions', sa.Column('patient_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'evolutions', type_='foreignkey')
    op.create_foreign_key(None, 'evolutions', 'patients', ['patient_id'], ['id'])
    op.drop_column('evolutions', 'internment_id')
    op.drop_column('evolutions', 'professional')
    op.drop_table('pendings')
    op.drop_table('prescriptions')
    op.drop_table('internments')
    op.drop_table('drug_prescriptions')
    op.drop_table('vitals')
    op.drop_table('resting_activities')
    op.drop_table('nursing_activities')
    op.drop_table('drugs')
    op.drop_table('diets')
    # ### end Alembic commands ###
